[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/leetcode"
  to = "/.netlify/functions/leetcode"
  status = 200
  force = true

[[redirects]]
  from = "/api/linkedin"
  to = "/.netlify/functions/linkedin"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
